CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230915204225_Initialization') THEN
    CREATE TABLE "Inhabitant" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" nvarchar(100) NOT NULL,
        "LastName" nvarchar(100) NOT NULL,
        "FatherName" nvarchar(100) NOT NULL,
        "Email" text,
        "Phone" text,
        "Address" text,
        "Birthdate" date NOT NULL,
        "IsMarried" boolean NOT NULL DEFAULT FALSE,
        "Created" timestamp with time zone NOT NULL,
        "CreatedBy" text,
        "LastModified" timestamp with time zone,
        "LastModifiedBy" text,
        CONSTRAINT "PK_Inhabitant" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230915204225_Initialization') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230915204225_Initialization', '8.0.0-rc.1.23419.6');
    END IF;
END $EF$;
COMMIT;

