CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919181751_Initialization') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dbo') THEN
            CREATE SCHEMA dbo;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919181751_Initialization') THEN
    CREATE TABLE dbo."Inhabitant" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" varchar(100) NOT NULL,
        "LastName" varchar(100) NOT NULL,
        "FatherName" varchar(100) NOT NULL,
        "Email" text,
        "Phone" text,
        "Address" text,
        "Birthdate" date NOT NULL,
        "IsMarried" boolean NOT NULL DEFAULT FALSE,
        "CreatedDateTime" timestamp NOT NULL,
        "ModifiedDateTime" timestamp,
        "CreatedByUserId" int,
        "ModifiedByUserId" int,
        CONSTRAINT "PK_Inhabitant" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919181751_Initialization') THEN
    CREATE INDEX "IX_Inhabitant_LastName_FirstName" ON dbo."Inhabitant" ("LastName", "FirstName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20230919181751_Initialization') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20230919181751_Initialization', '8.0.0-rc.1.23419.6');
    END IF;
END $EF$;
COMMIT;

