global:
  scrape_interval: 5s  # Set the scrape interval to X seconds

# alerting:
#   alertmanagers:
#     - static_configs:
#       - targets:
#         - alert-manager:9093

# rule_files:
#   - "alert_rules.yml"  # Define alerting rules in a separate file

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: "prometheus-node-exporter"
    static_configs:
      - targets: 
        - node-exporter:9100

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:8080"]
  
  - job_name: "village"
    static_configs:
      - targets: 
        - village:9100