version: '3.8'

services:
  village:
    image: registry.gitlab.com/docker7834340/ouijjane/village-api:latest
    container_name: village-api
    ports:
      - 1001:1001
      - 2001:2001
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:2001;http://+:1001
      - ASPNETCORE_HTTPS_PORT=2001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks: 
      - ouijjane
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=5433
    volumes:
      - postgres-data:/data/db
    networks:
      - ouijjane
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.intial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xms515m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-data:/usr/share/elasticsearch/data
    networks:
      - ouijjane

  kb01:
    container_name: kb01
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - ouijjane

volumes:
  postgres-data:
  es01-data:

networks:
  ouijjane:    


# eshop-mq:
#     image: rabbitmq:3.11.7-management
#     container_name: Queue
#     hostname: eshop-queue
#     volumes:
#         - ./.containers/queue/data/:/var/lib/rabbitmq
#         - ./.containers/queue/log/:/var/log/rabbitmq
#     environment:
#         RABBITMQ_DEFAULT_USER: guest
#         RABBITMQ_DEFAULT_PASS: guest