name: dotnet ci-cd

on:
  push:
    branches: [main, staging]
    tags: ['*']
  pull_request:
    branches: [main, staging]

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal

  village_api:
    name: build village api image
    needs: build
    uses: ./.github/workflows/docker-workflow.yml
    with:
      PROJECT_MODULE: "Village"
      PROJECT_COMPONENT: "Api"
      PROJECT_SUBPATH: ""
    secrets: inherit