name: dotnet ci-cd

on:
  push:
    branches: [main, staging, integration]
  pull_request:
    branches: [main, staging, integration]
  workflow_dispatch:
    inputs:
      build_images:
        type: boolean
        description: push microservices' images

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal

  build_village_api_image:
    needs: build
    uses: ./.github/workflows/docker-workflow.yml
    with:
          PROJECT_MODULE: "Village"
          PROJECT_COMPONENT: "Api"
          PROJECT_SUBPATH: ""
    secrets: inherit